/** @format */

export const INSTRUCTOR_REGISTER_REQUEST = "INSTRUCTOR_REGISTER_REQUEST";
export const INSTRUCTOR_REGISTER_SUCCESS = "INSTRUCTOR_REGISTER_SUCCESS";
export const INSTRUCTOR_REGISTER_FAIL = "INSTRUCTOR_REGISTER_FAIL";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";

export const STUDENT_DISPLAY_REQUEST = "STUDENT_DISPLAY_REQUEST";
export const STUDENT_DISPLAY_SUCCESS = "STUDENT_DISPLAY_SUCCESS";
export const STUDENT_DISPLAY_FAIL = "STUDENT_DISPLAY_FAIL";

export const INSTRUCTOR_DISPLAY_REQUEST = "INSTRUCTOR_DISPLAY_REQUEST";
export const INSTRUCTOR_DISPLAY_SUCCESS = "INSTRUCTOR_DISPLAY_SUCCESS";
export const INSTRUCTOR_DISPLAY_FAIL = "INSTRUCTOR_DISPLAY_FAIL";
