export const CREATE_BATCH_REQUEST = "CREATE_BATCH_REQUEST";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";
export const CREATE_BATCH_FAIL = "CREATE_BATCH_FAIL";

export const GET_BATCH_REQUEST = "GET_BATCH_REQUEST";
export const GET_BATCH_SUCCESS = "GET_BATCH_SUCCESS";
export const GET_BATCH_FAIL = "GET_BATCH_FAIL";

export const GET_ALL_BATCH_REQUEST = "GET_ALL_BATCH_REQUEST";
export const GET_ALL_BATCH_SUCCESS = "GET_ALL_BATCH_SUCCESS";
export const GET_ALL_BATCH_FAIL = "GET_ALL_BATCH_FAIL";

export const DELETE_BATCH_REQUEST = "DELETE_BATCH_REQUEST";
export const DELETE_BATCH_SUCCESS = "DELETE_BATCH_SUCCESS";
export const DELETE_BATCH_FAIL = "DELETE_BATCH_FAIL";

export const UPDATE_BATCH_REQUEST = "UPDATE_BATCH_REQUEST";
export const UPDATE_BATCH_SUCCESS = "UPDATE_BATCH_SUCCESS";
export const UPDATE_BATCH_FAIL = "UPDATE_BATCH_FAIL";
