/** @format */

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL";
export const COURSE_CREATE_RESET = "COURSE_CREATE_RESET";

export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL";

export const COURSE_GET_ALL_REQUEST = "COURSE_GET_ALL_REQUEST";
export const COURSE_GET_ALL_SUCCESS = "COURSE_GET_ALL_SUCCESS";
export const COURSE_GET_ALL_FAIL = "COURSE_GET_ALL_FAIL";

export const COURSE_GET_DETAILS_REQUEST = "COURSE_GET_DETAILS_REQUEST";
export const COURSE_GET_DETAILS_SUCCESS = "COURSE_GET_DETAILS_SUCCESS";
export const COURSE_GET_DETAILS_FAIL = "COURSE_GET_DETAILS_FAIL";

export const COURSE_ADD_LESSON_REQUEST = "COURSE_ADD_LESSON_REQUEST";
export const COURSE_ADD_LESSON_SUCCESS = "COURSE_ADD_LESSON_SUCCESS";
export const COURSE_ADD_LESSON_FAIL = "COURSE_ADD_LESSON_FAIL";

export const COURSE_DELETE_LESSON_REQUEST = "COURSE_DELETE_LESSON_REQUEST";
export const COURSE_DELETE_LESSON_SUCCESS = "COURSE_DELETE_LESSON_SUCCESS";
export const COURSE_DELETE_LESSON_FAIL = "COURSE_DELETE_LESSON_FAIL";
export const COURSE_DELETE_LESSON_RESET = "COURSE_DELETE_LESSON_RESET";

export const COURSE_ADD_ANNOUNCEMENT_REQUEST =
  "COURSE_ADD_ANNOUNCEMENT_REQUEST";
export const COURSE_ADD_ANNOUNCEMENT_SUCCESS =
  "COURSE_ADD_ANNOUNCEMENT_SUCCESS";
export const COURSE_ADD_ANNOUNCEMENT_FAIL = "COURSE_ADD_ANNOUNCEMENT_FAIL";

export const COURSE_DELETE_ANNOUNCEMENT_REQUEST =
  "COURSE_DELETE_ANNOUNCEMENT_REQUEST";
export const COURSE_DELETE_ANNOUNCEMENT_SUCCESS =
  "COURSE_DELETE_ANNOUNCEMENT_SUCCESS";
export const COURSE_DELETE_ANNOUNCEMENT_FAIL =
  "COURSE_DELETE_ANNOUNCEMENT_FAIL";
