/** @format */

export const CREATE_INSTITUTE_REQUEST = "CREATE_INSTITUTE_REQUEST";
export const CREATE_INSTITUTE_SUCCESS = "CREATE_INSTITUTE_SUCCESS";
export const CREATE_INSTITUTE_FAIL = "CREATE_INSTITUTE_FAIL";

export const GET_INSTITUTE_REQUEST = "GET_INSTITUTE_REQUEST";
export const GET_INSTITUTE_SUCCESS = "GET_INSTITUTE_SUCCESS";
export const GET_INSTITUTE_FAIL = "GET_INSTITUTE_FAIL";

export const GET_ALL_INSTITUTE_REQUEST = "GET_ALL_INSTITUTE_REQUEST";
export const GET_ALL_INSTITUTE_SUCCESS = "GET_ALL_INSTITUTE_SUCCESS";
export const GET_ALL_INSTITUTE_FAIL = "GET_ALL_INSTITUTE_FAIL";

export const DELETE_INSTITUTE_REQUEST = "DELETE_INSTITUTE_REQUEST";
export const DELETE_INSTITUTE_SUCCESS = "DELETE_INSTITUTE_SUCCESS";
export const DELETE_INSTITUTE_FAIL = "DELETE_INSTITUTE_FAIL";

export const UPDATE_INSTITUTE_REQUEST = "UPDATE_INSTITUTE_REQUEST";
export const UPDATE_INSTITUTE_SUCCESS = "UPDATE_INSTITUTE_SUCCESS";
export const UPDATE_INSTITUTE_FAIL = "UPDATE_INSTITUTE_FAIL";
